image: debian/buster
packages:
  - bash-completion
  - bison
  - debhelper
  - default-jdk
  - g++
  - gcc
  - gdb
  - gfortran
  - groff-base
  - libblas-dev
  - libbz2-dev
  - libcairo2-dev
  - libcurl4-openssl-dev
  - libxml2-dev
  - libjpeg-dev
  - liblapack-dev
  - liblzma-dev
  - libncurses5-dev
  - libpango1.0-dev
  - libpcre3-dev
  - libpng-dev
  - libreadline-dev
  - libtiff5-dev
  - libx11-dev
  - libxt-dev
  - mpack
  - pandoc
  - pandoc-citeproc
  - pandoc-data
  - subversion
  - tcl8.6-dev
  - texinfo
  - texlive-base
  - texlive-extra-utils
  - texlive-fonts-extra
  - texlive-fonts-recommended
  - texlive-generic-recommended
  - texlive-latex-base
  - texlive-latex-extra
  - texlive-latex-recommended
  - tk8.6-dev
  - x11proto-core-dev
  - xauth
  - xdg-utils
  - xfonts-base
  - xvfb
  - zlib1g-dev
  - ed
  - less
  - locales
  - vim-tiny
  - wget
  - ca-certificates
  - fonts-texgyre
  - libssl-dev
  - libcurl4-openssl-dev
  - r-base
  - r-base-dev
  - r-recommended
  - r-cran-crayon
  - r-cran-curl
  - r-cran-desc
  - r-cran-httr
  - r-cran-jsonlite
  - r-cran-devtools
  - r-cran-knitr
  - r-cran-rmarkdown
  - r-cran-rprojroot
  - r-cran-stringi
  - r-cran-testthat
  - r-cran-testit
  - r-cran-tidyverse
  - r-cran-xml2
environment:
  R_PACKAGE: tdigest
sources:
  - https://git.sr.ht/~hrbrmstr/tdigest
tasks:
  - setup: |
      wget "https://git.sr.ht/~hrbrmstr/sourcehut/blob/master/inst/helpers/build-helper.sh"
      chmod 755 build-helper.sh
      . ./build-helper.sh
      setup_locale
      setup_cran_repo
      setup_compiler
      setup_java

  - build: |
      . ./build-helper.sh
      install_deps
      build_and_check
